### ISSUE TITLE
Stuck on Pwnware was received by Wallbox

### ISSUE THREAD

**Issue by andreaconfa** [jagheterfredrik/wallbox-pwn#15]
Hi,
I'm trying to root my Pulsar Plus wallbox with software version 6.4.14 but, when running the script, it always stops at "Pwnware was received by Wallbox" and then nothing happens.

Is my wallbox compatible?
How i can solve the problem?

**Comment by filipeesch** [comment]
I have the same problem. Same wallbox and software version.

**Comment by jagheterfredrik** [comment]
It currently only works for firmware v5.x, some Wallboxes can be downgraded by factory reset
