### ISSUE TITLE
BleakError(f"{fail_msg}: Unreachable"

### ISSUE THREAD

**Issue by gllmlbrt** [jagheterfredrik/wallbox-pwn#19]
Hi, 

Starting by saying that I had my Wallbox Copper SB rooted, SSHd and MQTT was working great fully intgrated in HA. So I have done it once already. Thanks a lot for that !

Then I accidentally like an idiot upgraded to the latest 6.6 firmware which made me loose all of it.
I proceeded to downgrade to 5.2 with a restore. all good so far.

However now, when I run the ``python wallbox-pwn.py`` i get the following error log:
```
C:\Users\gual\python\wallbox>python wallbox-pwn.py
Please choose Wallbox:
0) WB232225 (8C:F6:81:33:34:E1)
> 0
Identified Bluetooth chip: BGX
Traceback (most recent call last):
  File "C:\Users\gual\python\wallbox\wallbox-pwn.py", line 149, in <module>
    asyncio.run(main())
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\gual\python\wallbox\wallbox-pwn.py", line 102, in main
    await wb.connect(wallboxes[chosen_idx])
  File "C:\Users\gual\python\wallbox\wallbox-pwn.py", line 50, in connect
    await self.client.start_notify(self.device_definition.tx, self.handle_rx)
  File "C:\Python312\Lib\site-packages\bleak\__init__.py", line 844, in start_notify
    await self._backend.start_notify(characteristic, wrapped_callback, **kwargs)
  File "C:\Python312\Lib\site-packages\bleak\backends\winrt\client.py", line 980, in start_notify
    _ensure_success(
  File "C:\Python312\Lib\site-packages\bleak\backends\winrt\client.py", line 168, in _ensure_success
    raise BleakError(f"{fail_msg}: Unreachable")
bleak.exc.BleakError: Could not start notify on 0019: Unreachable

```

I went through the all the previously closed issues and other methods I had employed in my first time in June. No success.
What could have changed that I am missing ?

**Comment by jagheterfredrik** [comment]
Not sure. Can you try an older version, e.g. https://github.com/jagheterfredrik/wallbox-pwn/tree/1ec25281b6b70f3546cb8fa2f4276508e39d8213 ?

**Comment by gllmlbrt** [comment]
Could it be related to a specific version of python and/or bleak ?

Which version should I ensure ?

**Comment by jagheterfredrik** [comment]
Sounds like an issue with your computer. Tried reboot and/or disable+enable bluetooth?

**Comment by gllmlbrt** [comment]
Soooo, i typically try that, and in this case I did not, and I suddenly had a "Sir have you tried rebooting your comuter ?" moment from the average hotline tech support dealing with granpa's issue.
I now restared the computer, and reset the bluetooh device, and it worked. My deepest apologies for wasting your time with this.
