### ISSUE TITLE
Not working on firmware version 6+

### ISSUE THREAD

**Issue by igoraj** [jagheterfredrik/wallbox-pwn#2]
Hej @jagheterfredrik, interesting work you did in this repo. I own a Pulsar Max and although on the outside it seems to be supporting the same mechanics in regards to BLE updates (same service-id, etc), it does however appear that the same method of pwning doesn't work on this model.

Do you mind sharing more details how did you came to construct the original pwn method for Pulsar Plus that I could use maybe to try and adapt for Max?

**Comment by jagheterfredrik** [comment]
I'm surprised it doesn't work. What do you get when trying?

**Comment by igoraj** [comment]
The procedure goes through smoothly, but the SSH still does not accept the key afterwards. I think they changed a designed a bit went with some other compute module than rpi, so it might be that at least paths have changed if not also for something else.

**Comment by jagheterfredrik** [comment]
What's your firmware version?

**Comment by igoraj** [comment]
[6.1.13](https://support.wallbox.com/en/rn/release-of-30th-november-2023/), I guess if I perform factory reset it might get rolled back to something earlier, but not sure whether that would be 5.17.44 or something older.

**Comment by jagheterfredrik** [comment]
Interesting. Wallbox promised to fix it in v6 so try rollback through restore. V6 is not yet available for Pulsar Pro

**Comment by tronikos** [comment]
Fix what?

**Comment by jagheterfredrik** [comment]
The rooting procedure

**Comment by tronikos** [comment]
Thanks. Good to know to not install any updates. It would be good to mention it in the readme.

**Comment by ReTaec** [comment]
Are there any updates if your PulsarPlus is now running on 6.1.19? Do you think it could run on v6+ also?

**Comment by jagheterfredrik** [comment]
I’ve heard it runs fine if you root on 5 then upgrade. To root, do a restore to 5 then upgrade again. For now.

**Comment by ReTaec** [comment]
Thanks for the quick answer. How can i restore / downgrade the wallbox to v5? Havent found anything jet online :S Online is still also available after rooting?

**Comment by jagheterfredrik** [comment]
Wallbox app, advanced -> restore. What version you get depends on what box you have

**Comment by jagheterfredrik** [comment]
Cloud is unaffected by rooting

**Comment by ReTaec** [comment]
Awesome, thank you very much! 
As info for everyone reading this. Currently resetting a Pulsar Plus Wallbox from version 6.1.19 brings the version down to 4.7.6
Will try to root it tomorrow but i expect no issues ;) Highly apprechiated your effort

**Comment by jagheterfredrik** [comment]
Oh cool didn't even realize they released v6 for Pulsar Plus, happend Jan 10 👍 

Do note that different Wallboxes will end up on different versions when restoring, i.e. the latest at time of their manufacturing. Mine restores to 5.x.x.

**Comment by ReTaec** [comment]
Tried today to root the Wallbox, but it stucks on "Wallbox is processing pwnware..." - When checking the hup_data.get('st') it has the value 'fail'. Do you have any idea how to debug any further?

**Comment by jagheterfredrik** [comment]
It is supposed to fail

**Comment by ReTaec** [comment]
![image](https://github.com/jagheterfredrik/wallbox-pwn/assets/101642731/290f166c-34df-4a99-aca1-096ac1c2955d)
yep tried but looks wrong to me :S

**Comment by jagheterfredrik** [comment]
See #3

**Comment by ReTaec** [comment]
i think you got me wrong :) when i try to root my Wallbox i only get:

python wallbox-pwn.py
Please choose Wallbox:
0) WB421337 (XX:XX:X:XX:XX:XX)
> 0
Identified Bluetooth chip: Zentri
Setting Wallbox to AP mode
Wallbox AP is ready, connect to WB421337-Hotspot using password XXXPassXXX, then press return
>
Sending pwnware
Pwnware was received by Wallbox


And thats all :S It never comes to "processing" or "pwnd successfully"
I restored the Wallbox several times today,

**Comment by jagheterfredrik** [comment]
I understand and would still like to see if ssh works. If the connection is rejected you’ll get “ Permission denied (publickey)”. If you get another error the rooting might’ve worked but your ssh client is not behaving.

**Comment by ReTaec** [comment]
I' now getting exact this 
![image](https://github.com/jagheterfredrik/wallbox-pwn/assets/101642731/dfe88d29-398e-445f-9be1-7a9b8bc25c78)

**Comment by jagheterfredrik** [comment]
Please include the command 🙏

**Comment by ReTaec** [comment]
ssh -i id_rsa root@192.168.178.146
root@192.168.178.146: Permission denied (publickey).

Or

ssh -i id_rsa root@192.168.178.146 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa
command-line: line 0: Bad configuration option: pubkeyacceptedalgorithms

**Comment by jagheterfredrik** [comment]
And this is after a rooting attempt? How did you fix the “invalid format” issue you had previously?

**Comment by ReTaec** [comment]
yep this is afer the rooting attempt where i did the screenshot (with the red arrows)
i reloaded the repo once again from git and now it has no format issue. The code etc is also brand new, expect for those two additional "print" statements

**Comment by jagheterfredrik** [comment]
I think next step would be to try upgrade to v5, I have dumps but don’t want to publish them. DM me here perhaps https://community.home-assistant.io/t/wallbox-pulsar-plus-integration/200339/1036

**Comment by igoraj** [comment]
I parked this for a while since it didn't work at the time of pwning, but I recently tried connecting again and was able to ssh just fine. I suspect some powercycle must have sorted out situation.
Pulsar Max, version is still at 6.1.13 

From my perspective this ticket can be closed.

**Comment by lostOzone** [comment]
> I parked this for a while since it didn't work at the time of pwning, but I recently tried connecting again and was able to ssh just fine. I suspect some powercycle must have sorted out situation. Pulsar Max, version is still at 6.1.13
> 
> From my perspective this ticket can be closed.

So it worked with version 6.1.13?

**Comment by igoraj** [comment]
Interesting update. It seems it again stopped working for me, I'm getting public key denied errors again. So I'm wondering if this version implements some kind of security measures on firewall that get triggered by failed auth attempts. Restarting Wallbox did not help.
