### ISSUE TITLE
Unable to connect to Access Point

### ISSUE THREAD

**Issue by ronaldt80** [jagheterfredrik/wallbox-pwn#5]
I walked through the full script (using Anaconda) - no issue connecting to the WB through bluetooth, access point in created etc.

When I try to connect my laptop to the access point I get stuck. It requests a pin of 8 digits, so I click "connect using a security key instead" and proceed with entering the password. No luck.. any thoughts?

```
(base) C:\Users\msn>python wallbox-pwn.py
Please choose Wallbox:
0) WB297036 (8C:F6:81:38:43:21)
> 0
Identified Bluetooth chip: BGX
Setting Wallbox to AP mode
Wallbox AP is ready, connect to WB297036-Hotspot using password REDACTED, then press return
>
```

Note, not sure if the comma is part of the password, but I tried both with and without the comma 😄

**Comment by jagheterfredrik** [comment]
Comma is not part of the password. When you say “no luck”, you mean you get “incorrect password”?

**Comment by ronaldt80** [comment]
Thanks - don't know how / why but after the 15th time it suddenly did work. Once connected the first attempt gave a time out, second was successful.

Out of curiosity, I could see my neighbours wallbox as well; realize the WB firmware 6 will solve this issue but is it possible to secure mine with your local software to avoid abuse going forward? (looking at the way my neighbours are using their WB I doubt any of them is sufficiently tech savvy to explore github but just to be sure..)
