### ISSUE TITLE
Compatible: Wallbox copper SB

### ISSUE THREAD

**Issue by sincze** [jagheterfredrik/wallbox-pwn#8]
Update: 11-04-24: 
Yes, it Will work with Wallbox Copper SB (FW 5.17.87)

Would this also be compatible with my Wallbox Copper SB?
That has a LAN port ;-) (FW 5.17.87)

![20230801_114342](https://github.com/jagheterfredrik/wallbox-pwn/assets/5776333/2a2f5a38-2f1e-4e3e-93ac-5d6f8dd32406)

**Comment by jagheterfredrik** [comment]
Try

**Comment by lostOzone** [comment]
It works. I restored it to factory before.

**Comment by sincze** [comment]
> It works. I restored it to factory before.

Tnx.
Restored because the PWN did not work according to plan? 
Just calculating risks here ;-)

**Comment by lostOzone** [comment]
Sorry I don't remember any issue with WIFI. I did from a MacBook then ssh from Windows 11 PC.

**Comment by sincze** [comment]
Ok, maybe add to the manual 1 line of code ;-)

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for 'id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "id_rsa": bad permissions
root@192.168.**.**: Permission denied (publickey).

`sudo chmod 400 id_rsa`

Will fix that issue.

**Comment by sincze** [comment]
Script is compatible with the Wallbox copper SB (FW 5.17.87)
